# CV/Cover Letter Generator Configuration
# Copy this file to config.yaml and update with your settings

openai:
  api_key: "your-openai-api-key-here"  # Get from https://platform.openai.com/api-keys
  model: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 2000

logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_handler: true
  console_handler: true

application:
  output_directory: "applications"
  template_directory: "templates"
  cache_directory: "cache"
  max_concurrent_jobs: 3